version: '3.6'
volumes:
  dbdata:
services:
  db:
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db/postgres"
      SECRET_KEY_BASE: "22029186ec84ea09dd45aa8c62a7404ac630216a25f2cb436b98272695fc5409e1471887568b6e9e27832368102f5962647df747f515d11c515ee36258d7fd04"
