version: "3.8"
services:
  database:
    image: postgres:11.5
    environment:
      POSTGRES_DB: govuk
      POSTGRES_USER: govuk
      POSTGRES_PASSWORD:
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    volumes:
      - .:/code:cached
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      RAILS_ENV: development
      DATABASE_NAME: govuk
      DATABASE_USER: govuk
      DATABASE_PASSWORD:
      DATABASE_HOST: database
volumes:
  db_data:
